version: '3'
services:
 checker:
  build:
   context: .
   dockerfile: Dockerfile-checker 
  container_name: cex-stock-checker
  volumes:
   - './checker:/working/'
  tty: true
  restart: always
 http:
  build: 
   context: .
   dockerfile: Dockerfile-http
  container_name: cex-http
  volumes:
   - './http:/web/'
  command: 'python /web/app.py'
  restart: always
  ports:
   - '80:80'